services:
  - type: web_service
    name: pingup-nginx
    env: docker
    branch: main
    plan: starter
    region: oregon
    dockerfilePath: Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    buildCommand: ''
    envVars:
      - key: PUBLIC_ORIGIN
        value: 'https://your-domain.com'
